### ISSUE TITLE
Wrong calculation for recipes that produce multiple items

### ISSUE THREAD

**Issue by Glichy** [Seggan/SFCalc#13]
A few examples:

![sfcalc_copper_wire](https://user-images.githubusercontent.com/7513879/100098970-ada0e500-2e56-11eb-9fac-4116964fe553.png)

![sfcalc_cloth](https://user-images.githubusercontent.com/7513879/100099067-d1642b00-2e56-11eb-88ee-a35fc71a36a4.png)

![sfcalc_rune](https://user-images.githubusercontent.com/7513879/100099078-d628df00-2e56-11eb-8d05-57acc9f8c05f.png)

**Comment by Seggan** [comment]
I am aware of this issue. Unfortunately, it'd be kind of challenging to cache every item that has multiple outputs and then optimize the calculation for that. However, I will look into it.

**Comment by MrPolloo** [comment]
Is this bug still exist?

**Comment by Seggan** [comment]
Yes. Otherwise it'd be closed
