### ISSUE TITLE
Not clickable items in the GUI

### ISSUE THREAD

**Issue by MrLarkyy** [Seggan/SFCalc#15]
Hey! I just downloaded the latest version from January, but it is kinda buggy. When I type /sfcalc, it opens the GUI, but when I click on a category, it just closes the menu and doesn't show up anything... (Only last category works, but other not)

**Comment by Seggan** [comment]
Any console errors?

**Comment by MrLarkyy** [comment]
> Any console errors?

Nope

**Comment by MrLarkyy** [comment]
I will try to choose other categories, one sec

**Comment by MrLarkyy** [comment]
Someone it sends this error
https://pastebin.com/vHyW63VS

Can you make an option to totally disable the GUI? So there will be one help message, when a player types just /sfcalc

**Comment by MrLarkyy** [comment]
> Any console errors?

it looks like, it opens a submenu only when I click on addon's category. But regular categories don't work

**Comment by Seggan** [comment]
Ah yes, thats because categories of size above 54 are not supported yet. For now use the command form of the calculator.

**Comment by MrLarkyy** [comment]
> Ah yes, thats because categories of size above 54 are not supported yet. For now use the command form of the calculator.

Do you think that you can add an option to disable the GUI? It would be nice ^^ (As the menu is still in progress)

**Comment by Seggan** [comment]
Perhaps later. I am currently busy with my other addons.

**Comment by Seggan** [comment]
> > Ah yes, thats because categories of size above 54 are not supported yet. For now use the command form of the calculator.
> 
> Do you think that you can add an option to disable the GUI? It would be nice ^^ (As the menu is still in progress)

The newer builds (I forgot which one exactly) remove the GUI so this issue is now invalid
