### ISSUE TITLE
Sfcalc stopped working correctly after Sfcalc version 16

### ISSUE THREAD

**Issue by Derpylove** [Seggan/SFCalc#17]
After updating from Sfcalc version 15 -> 16 Sfcalc broke.
https://pastebin.com/pCJXjRGz

When doing /sfcalc (item) it will show this 
![image](https://user-images.githubusercontent.com/45398741/113328442-939f7380-931c-11eb-85d1-1edf49895bdf.png)
Example of battery ^
![image](https://user-images.githubusercontent.com/45398741/113329025-57204780-931d-11eb-93ee-cb37859d4492.png)

![image](https://user-images.githubusercontent.com/45398741/113328886-26401280-931d-11eb-8280-f614ab84b164.png)

After seeing that it was broken we decided to go back to Sfcalc version 15 and it started working again with no issues.

**Comment by Seggan** [comment]
Regenerate the SFCalc config files. Build 16 added a new formatting system which needs to have the config regenerated

**Comment by TheLittleCube** [comment]
> Regenerate the SFCalc config files. Build 16 added a new formatting system which needs to have the config regenerated

This worked for me. Everything back to normal. Thank you.
