### ISSUE TITLE
Suggestion: sfcalcremaining

### ISSUE THREAD

**Issue by NCBPFluffyBear** [Seggan/SFCalc#2]
Add a command that calculates how much more of an item a player needs based on what they already have in their inventory.

Example display:
![image](https://user-images.githubusercontent.com/31554056/92268023-469f1000-eea7-11ea-9c55-3ad4e5310608.png)

**Comment by Seggan** [comment]
I prefer this one over crossing off. I think i will call it /sfcremaining
