### ISSUE TITLE
Could not load

### ISSUE THREAD

**Issue by neilcicierega** [Seggan/SFCalc#21]
[11:08:47] [Server thread/ERROR]: Could not load 'plugins\SFCalc-24.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: io/github/seggan/sfcalc/SFCalc has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Seggan** [comment]
Update your Java version. SFCalc only supports Java 11 or above
