### ISSUE TITLE
Setting use-carbon-instead-of-coal not working

### ISSUE THREAD

**Issue by EpicPlayerA10** [Seggan/SFCalc#29]
Calculating other materials which use carbon, shows coal instead of carbon. Must have `use-carbon-instead-of-coal` set to true.
Probably caused by #27

**Comment by EpicPlayerA10** [comment]
And previous patch doesn't fix that:
![obraz](https://user-images.githubusercontent.com/62206933/130257037-db34eca9-9519-403a-bb45-afd4b060e206.png)

**Comment by Seggan** [comment]
> And previous patch doesn't fix that:
> ![obraz](https://user-images.githubusercontent.com/62206933/130257037-db34eca9-9519-403a-bb45-afd4b060e206.png)

Intended
