### ISSUE TITLE
/sfcalc shows improper amount of coal needed.

### ISSUE THREAD

**Issue by Skizzles** [Seggan/SFCalc#8]
**All these show items that show incorrect amounts of coal needed. 
Carbon: https://gyazo.com/f52a695459549174bcc91df32565cf33
Compressed Carbon: https://gyazo.com/fa809959d46ea2fd3dea36589c39bbfe
Carbon Chunk: https://gyazo.com/59e3e613b503f27b5e5cdf60036f393e
Reinforced alloy: https://gyazo.com/d508a3e5738804a4bda6f7f6950134a7
Hardened metal: https://gyazo.com/0a34195fa49d4cff8b2ee733d3b47423
Steel: https://gyazo.com/a5d4f05edc8ccd76a4a69c5f72c8278c
Damascus Steel: https://gyazo.com/e1d8e00098eb5013ce8f8530106ee281

**Comment by Seggan** [comment]
@Skizzles SFCalc version?

**Comment by Skizzles** [comment]
@Seggan This would be on vDev 13 now. Still showing the same for me.

**Comment by Seggan** [comment]
This has been fixed in build 13; try it out now.

**Comment by Skizzles** [comment]
Uninstalled addon, closing as solved lmao
